### ISSUE TITLE
Issue using action with Node 14

### ISSUE THREAD

**Issue by rafistrauss** [c2corg/browserslist-update-action#303]
Very much appreciate this action; I've been adding it to many of my org's repos since I found out about it.

Is there any way to specify the version of Node this action should use? I have a project that can't yet be migrated to Node 16 and the npm install fails in this action.
Thanks!

**Comment by brunobesson** [comment]
Hi, thanks for your feedback. I am currently on holidays, I'll have a look in September 🙂

**Comment by rafistrauss** [comment]
> Metadata syntax allows to run either node 12 or 16, not 14
😵 

Yeah v1.2.2 sounds like it should work perfectly; def. don't want to make you crazy for what should (hopefully) be a short-lived use case. Thanks so much!!
